apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snyk-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/odrodrig/nodejs-goof
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: code-analysis
      taskRef:
        name: snyk-node
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace